#
# UnraveledMCMod Configuration
# by Madgeek1450, Prozza, and CreeperSeth
#

# Generic server information
server:
  # You should change this to your server's name
  name: UnraveledMC

  # The address your server is located at. Please do not include the port.
  address: play.unraveledmc.com

  # All players who show up as owner
  owners:
    - Skoonk_and_Xeoda
    - RobinGall2910

  # All players whos how up as founder
  founders:
    - AwesomePinch
    - aggelosQQ

  # All players who show up as executive
  execs:
    - irix
    - bobscog
    - TheHour
    - Mark_the_Dragon
    
  # All players who show up as donators
  donors: []

  # All players who show up as master builder
  master_builders: []

  # URL players should appeal for bans at
  ban_url: http://unraveledmc.com/forum/

  # URL players should appeal for permanent bans at
  permban_url: http://unraveledmc.com/forum/
  
# Shown at the server list
motd:
  # Every word in the MOTD will be a different color unless prefixed by a color code
  colorful_motd: true

  # What shows up on line 1
  line_one: '&lUnraveledMC &l- &lFree &lOP'
  
  # What shows up on line 2
  line_two: 'Running on %mcversion%'  

# The discord bot self verification system
verification:
  # Should this be enabled?
  enabled: false
  
  # If you do not know the bot token or don't have a bot created, you can do so at https://discordapp.com/developers/applications/me
  # A token must be specified if you have enabled verification
  token: ''

# Should players be opped on join
op_on_join: true

# The shop
shop:
  # Enable the shop
  enabled: true
  
  # Shop prefix
  prefix: '&7&l[&8&lUMC Shop&7&l]'
  
  # How much should colored chat cost
  colored_chat_price: 50
  
  # How much should login messages cost
  login_message_price: 100
  
  # How much should the Thor Hammer cost
  thor_hammer_price: 150
  
  # How much should Crescent Rose cost
  crescent_rose_price: 300
  
  # How much should it cost a player to use Crescent Rose per attack
  crescent_rose_use_price: 15
  
  # How much should the minigun cost
  minigun_price: 200
  
# Staff
staff:
  # Message to display to staff members when they login (supports color codes and is multiple line)
  staff_login_message:
    - '&2Welcome back staff member!'
    - '&cBe sure to keep an eye on the ops!'
    
  # URL to the staff application template
  staff_application_url: 'https://f.unraveledmc.com'
  
  # Staff list
  stafflist:
    # The amount of hours after which staff members may be removed from the staff list
    clean_threshold_hours: 167
    # Give the default CONSOLE senior admin privileges.
    # Handy in development environments.
    console_is_senior: true

  # Staff-Only Mode
  staff_only_mode: false
  
  # IPs that can not be added to staff list entries
  nostaff_ips:
    - 123.123.123.123

# ForceIP configuration
forceip:
  enabled: false

  # The port players should use to connect to your server; only applies to forceip
  port: 25565

  # The kick message sent to players when logging in with the wrong hostname
  kickmsg: You have been kicked from the server - Please connect using %address%


# Blocking certain events
allow:
  fire_place: false
  fire_spread: false
  fluid_spread: false
  lava_place: false
  lava_damage: false
  water_place: false
  tnt_minecarts: false
  explosions: false
  firework_explosions: false

# Blocked commands:
#
# How blocked commands work:
# All sections described below are delimited by colon characters.
# Make sure that you block a command by its main command name, not an alias
# as all aliases are blocked by default. Commands are case-insensitive.
#
# * The first section is a letter which indicates which rank may use this command
#   Valid ranks:
#   n - Nobody (Completely disabled)
#   s - Senior Admins (Console)
#   a - Admins (Console)
#   m - Mods (Any in-game staff)
#   o - Ops (Non-Ops won't be able to use it)
#
# * The second section is a letter which indicates what to do when a player executes that command.
#   Valid actions:
#   b - Block the command
#   u - Block the command and Return an "Unknown command" message (Used to hide commands)
#
# * The third section is the command to be blocked, prefixed with a slash
#
# * The fourth section is the message to send to the player when executing that command.
#   This should be ommited if unwanted. ChatColors are supported with the &-key. By default
#   -the starting ChatColor is set to gray. You can use the default 'That command is blocked.' message
#   by using a single underscore.
#
# Examples:
#   - 'n:b:/mail sendall:&4You can't send mail to everyone!'
#   - 'n:b:/ban:_'
#
blocked_commands:
    # Disabled commands
  - 'n:b:/socialspy:_'
  - 'n:b:/time:Server-side time changing is disabled. Please use /ptime to set your own personal time.'
  - 'n:b:/gamemode:Use /creative and /survival to set your gamemode.'
  - 'n:b:/ban-ip:_'
  - 'n:b:/toggledownfall:_'
  - 'n:b:/effect:Please use /potion to set effects.'
  - 'n:b:/spreadplayers:_'
  - 'n:b:/execute:_'
  - 'n:b:/blockdata:_'
  - 'n:b:/clearhistory:_'
  - 'n:b:/save-all:_'
  - 'n:b:/save-on:_'
  - 'n:b:/save-off:_'
  - 'n:b:/skinsrestorer:_'
  - 'n:b:/packet:_'
  - 'n:b:/thaw:_'
  - 'n:b:/setjail:_'
  - 'n:b:/testfor:_'
  - 'n:b:/testforblock:_'
  - 'n:b:/testforblocks:_'
  - 'n:b:/packet_filter:_'
  - 'n:b:/disguiseradius:_'
  - 'n:b:/undisguiseradius:_'
  - 'n:b:/disguiseplayer:_'
  - 'n:b:/undisguiseplayer:_'
  - 'n:b:/disguiseentity:_'
  - 'n:b:/undisguiseentity:_'
  - 'n:b:/spawnmob:_'
  - 'n:b:/maintenance:_'
  - 'n:b:/kill:_'
  - 'n:b:/tellraw:&clol nope'
  - 'n:b:/title:&clol nope'
  - 'n:b:/tpall:&cYou may not use this command.'
  - 'n:b:/clone:&cThis command has been disabled due to misuse.'
  - 'n:b:/mail sendall:_'
  - 'n:b:/entitydata:_'
  - 'n:b:/setworldspawn:_'
  - 'n:b:/trigger:_'
  
  # Staff commands
  - 'm:b:/kick:_'
  - 'm:b:/tool:_'
  - 'm:b:/replaceitem:_'
  - 'm:b://generate:_'
  - 'm:b://:_'
  - 'm:b:/superpickaxe:_'
  - 'm:b:/size:_'
  - 'm:b://mask:_'
  - 'm:b:/mat:_'
  - 'm:b://butcher:_'
  - 'm:b:/scoreboard:_'
  - 'm:b:/setspawn:_'
  - 'm:b://snow:_'
  - 'm:b:/forestgen:_'
  - 'm:b:/setidletimeout:_'
  - 'm:b:/eco reset:_'
  - 'm:b:/mask:_'
  - 'm:b:/gmask:_'
  - 'm:b:/lrbuild:_'
  - 'm:b:/defaultgamemode:_'
  - 'm:b:/reload:_'
  - 'm:b:/worldborder:_'
  - 'm:b:/weather:_'
  - 'm:b:/setblock:_'
  - 'm:b:/green:_'
  - 'm:b:/gamerule:_'
  - 'm:b:/togglejail:_'
  - 'm:b:/fill:_'
  - 'm:b:/flood:_'
  - 'm:b:/coreprotect:_'
  - 'm:b:/core:_'
  - 'm:b:/co:_'
  - 'm:b:/supertrails:_'
  - 'm:b:/protocol:_'
  - 'm:b:/tablist:_'
  - 'm:b:/aba:_'
  - 'm:b:/ab:_'
  - 'm:b:/timer:_'  
  - 'm:b:/sblist:_'
  - 'm:b:/adminvote:&cOnly staff members can do that, please use /vote'
  - 'm:b:/av:&cOnly staff members can do that, please use /vote'
  - 'm:b:/betterchairsreload:_'
  - 'm:b:/lb reload:_'
  - 'm:b:/enderchest:_'
  - 'm:b:/tphere:&cOnly staff members can use that! Please use /tpahere instead!'
  - 'm:b:/tpo:&cOnly staff members can use that! Please use /tp(a) instead!'
  - 'm:b:/tpohere:&cOnly staff members can use that! Please use /tpahere instead!'
  - 'm:b://count:_'
  - 'm:b:/pardon:_'
  - 'm:b:/pardon-ip:_' 
  - 'm:b:/locate:_'
  - 'm:b:/playsound:_'
  - 'm:b:/stopsound:_'
  - 'm:b:/summon:_'
  - 'm:b:/particle:_'
  - 'm:b:/stop:_'
  - 'm:b:/restart:_'

# Automatically wipe dropped objects
auto_wipe: true

# Nuking prevention
nukemonitor:
  enabled: true
  count_break: 100
  count_place: 40
  range: 10.0

freecam_trigger_count: 10
explosive_radius: 4.0

# Show all attempted commands in the log, will result in duplicate log messages
preprocess_log: true

# Disable certain events
disable:
  night: true
  weather: true


# Enable misc. features
landmines_enabled: false
mp44_enabled: false
tossmob_enabled: false
lightning_swing_enabled: true

# Moblimiter
moblimiter:
  enabled: false
  max: 2000
  disable:
    dragon: true
    ghast: true
    slime: true
    giant: true

# Flatlands
flatlands:
  generate: true

  # Flatlands generation parameters - Uses CleanroomGenerator syntax - http://dev.bukkit.org/server-mods/cleanroomgenerator/
  generate_params: 16,stone,32,dirt,1,grass

# Protected Areas - Protect areas so that only staff members can directly modify blocks in those areas. WorldEdit and other such plugins might bypass this.
protectarea:
  enabled: true
  auto_protect_spawnpoints: true
  auto_protect_radius: 25.0

# Host Sender Names -  that indicate automated services or host-based consoles you want to block from using some commands.
# Make sure these are all lower-caseNames.
host_sender_names:
  - rcon
  - remotebukkit

# Announcer
announcer:
  enabled: true

  # Interval between announcements, in seconds.
  interval: 600

  # Prefix for all announcements
  prefix: '&e&l[&7&lUnraveled&8&lMC&e&l] &6&l>> &e&l'

  announcements:
    - 'Be sure to visit our forums at &6https://f.unraveledmc.com'
    - 'You can always review the server rules here: &6https://f.unraveledmc.com'
    - 'If you are not opped, be sure to ask!'
    - 'Somebody breaking the rules? Report it! /report <user> <reason>'
    - 'Griefing is not allowed!'
    - 'Hacked clients are allowed as long as they do not harm the server!'
    - 'Interested in becoming a member of our staff team? Do "/si" for more information!'
    - 'You may view all online staff via "/list -s"'
    - 'Save your buildings via WorldEdit! https://f.unraveledmc.com for more information!'
    - 'We are an offline/cracked server!'
    - 'AwesomePinch, Skoonk_and_Xeoda, and RobinGall2910 are the owners of UnraveledMC.'
    - 'Server lagging? Check the lag via "/tps"'
    - 'AwesomePinch and aggelosQQ are the founders of UnraveledMC.'
    - 'You are allowed to record and stream videos on UnraveledMC.'
    - 'Spawn killing is forbidden!'
    - 'Invisible potions are allowed!'
    - 'Serial griefing and trolling will result in a permanent ban!'
    - 'Racism, nazism, and sexism are strictly forbidden!'
    - 'You can apply for master builder at https://f.unraveledmc.com'
    - 'Ever see players with colored chat and custom login messages? You can get them by doing /shop!'
    - 'Vote for us to receive &6&l5 Coins&a&l! &b&l/vote'

# Famous players - cannot join the server while onlinemode is turned off
famous_players:
  - honeydew
  - xephos
  - captainsparklez
  - truemu
  - kiershar
  - fvdisco
  - sethbling
  - notch
  - jeb_
  - gamechap
  - bertiechap
  - vechs
  - antvenom
  - chimneyswift
  - deadmau5
  - etho
  - ethoslab
  - skydoesminecraft
  - skythekidrs
  - tobyturner
  - xxslyfoxhoundxx
  - paulsoaresjr
  - sips_
  - deadlox
  - xxslyxx
  - jeromeasf
  - dinnerbone
  - grumm
  - grum
  - evilseph
  - cavemanfilms
  - herobrine
  - whiteboy7thst
  - stampylonghead
  - stampylongnose
  - dantdm
  - gizzy14gazza
  - furiousdestroyer
  - pewdie
  - thecampingrusher
  - logdotzip
  - ssundee
  - mrcrainer
  - achileis
  - donibobes
  - itsjerry
  - itsharry
  - bebopvox
  - clankstar
  - jollyajax
  - b0xx3r
  - vareide
  - defek7
  - strutt20
  - appleg
  - sterling_
  - hypixel

# Pet Protect - Prevent tamed pets from being killed.
petprotect:
  enabled: true

# Mojang service checker
service_checker_url: http://status.mojang.com/check

# HTTPD server
httpd:
  enabled: true
  port: 28366
  public_folder: ././././././././var/www/html

# Inactivity Auto-Kick (Requires Essentials)
autokick:
  enabled: true

  # Percentage of server player capacity used at which players will be automatically kicked for being inactive. Range: 0.0 - 1.0
  threshold: 0.9

  # Time, in seconds, after which a player should be kicked when inactive
  time: 120

# Players with access to the overlord command
overlord_ips: []
